name: generate sitemap

on:
  push:
    branches: [ master ]
    paths: [ '**.html' ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap

    steps:
    - name: notify start
      run: |
        echo "action started"

    - name: checkout the repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://sainternet.xyz/

    - name: output statistics
      run: |
        echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"

    - name: create pull request
      uses: peter-evans/create-pull-request@v5.0.0
      with:
        title: "update sitemap"
        body: >
          sitemap created by [checkout](https://github.com/actions/checkout), [generate-sitemap](https://github.com/cicirello/generate-sitemap) and [create-pull-request](https://github.com/peter-evans/create-pull-request)
        commit-message: "saint-lascivious.github.io: update sitemap"
        author: Hayden Pearce <saint-lascivious@users.noreply.github.com>
        committer: Hayden Pearce <saint-lascivious@users.noreply.github.com>
        branch: create-pull-request/sitemap
        delete-branch: true

    - name: notify completion
      run: |
        echo "action completed"
