name: generate xml sitemap

on:
  push:
    branches: [ master ]
    paths: [ '**.html' ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: generate a sitemap

    steps:
   &nbsp;<icon class="fa-solid fa-caret-right"></icon>&nbsp;name: checkout repo
      id: cr
      uses: actions/checkout@v3.3.0
      with:
        fetch-depth: 0

   &nbsp;<icon class="fa-solid fa-caret-right"></icon>&nbsp;name: generate sitemap
      id: gs
      uses: cicirello/generate-sitemap@v1.9.1
      with:
        base-url-path: https://sainternet.xyz/

   &nbsp;<icon class="fa-solid fa-caret-right"></icon>&nbsp;name: output stats
      run: |
        echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"

   &nbsp;<icon class="fa-solid fa-caret-right"></icon>&nbsp;name: create pull request
      id: cpr
      uses: peter-evans/create-pull-request@v4.2.3
      with:
        title: "automated sitemap update"
        body: >
          Sitemap updated by the [generate-sitemap](https://github.com/cicirello/generate-sitemap)
          GitHub action. Automated pull-request generated by the
          [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action.
        commit-message: "automated sitemap update"
        author: Hayden Pearce <saint-lascivious@users.noreply.github.com>
        committer: Hayden Pearce <saint-lascivious@users.noreply.github.com>
        branch: create-pull-request/sitemap
        delete-branch: true
