name: generate xml sitemap

on:
  push:
    branches: [ master ]
    paths: [ '**.html' ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: generate a sitemap

    steps:
    - name: checkout repo
      id: checkout_repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: generate sitemap
      id: generate_sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://sainternet.xyz/

    - name: output stats
      id: output_stats
      run: |
        echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"

    - name: create pull request
      id: create_pull_request
      uses: peter-evans/create-pull-request@v4.2.3
      with:
        title: "automated sitemap update"
        body: >
          Repository checked out by the [checkout](https://github.com/actions/checkout) GitHub action.
          Sitemap updated by the [generate-sitemap](https://github.com/cicirello/generate-sitemap) GitHub action.
          Automated pull-request generated by the [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action.
        commit-message: "automated sitemap update"
        author: Hayden Pearce <saint-lascivious@users.noreply.github.com>
        committer: Hayden Pearce <saint-lascivious@users.noreply.github.com>
        branch: create-pull-request/sitemap
        delete-branch: true
